import turtle
screen = turtle.Screen()
screen.bgcolor("black")
screen.title("Shapes")
t = turtle.Turtle()
t.speed(3)
t.pensize(3)
t.penup()
t.goto(-200, 0)
t.pendown()
t.color("red", "yellow")
t.begin_fill()
for i in range(3):
    t.forward(100)
    t.left(120)
t.end_fill()
t.penup()
t.goto(-50, 0)
t.pendown()
t.color("blue", "cyan")
t.begin_fill()
for i in range(2):
    t.forward(120)
    t.left(90)
    t.forward(70)
    t.left(90)
t.end_fill()
t.penup()
t.goto(150, 0)
t.pendown()
t.color("green", "lightgreen")
t.begin_fill()
for i in range(6):
    t.forward(60)
    t.left(60)
t.end_fill()